spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update # hoặc validate/create-drop nếu bạn cần
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: littlefox171103@gmail.com
    password: lnwxizujboahxwrw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: utf-8
  # i18n
  messages:
    basename: messages
    encoding: UTF-8

  # Thymeleaf configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html


